// Get All Bhakti
GET http://localhost:3000/bhakti/
###

// Get Bhakti by Id
GET http://localhost:3000/bhakti/2
###

// Get Bhakti By Type
GET http://localhost:3000/bhakti/type/3
###

// Get All Bhakti Filter Keywords
GET http://localhost:3000/bhakti/filter/options
###

// Get Bhakti By filter
GET http://localhost:3000/bhakti/filter?keyword=Guru&_category=2

###
// get all the categories
GET http://localhost:3000/bhakti/categories