// Get All Bhakti
GET http://localhost:3000/bhakti/
###

// Get Bhakti by Id
GET http://localhost:3000/bhakti/4
###

// Get Bhakti By Type
GET http://localhost:3000/bhakti/type/2
###

// Get All Bhakti Filter Keywords
GET http://localhost:3000/bhakti/filter/options
###

// Get Bhakti By filter1
GET http://localhost:3000/bhakti/filter?keyword[]=Devotion&_category=1

###
// get all the categories
GET http://localhost:3000/bhakti/categories

###
// get category by id
GET http://localhost:3000/bhakti/categories/2

###
// add category
POST http://localhost:3000/bhakti/categories

###
// update category by id
PUT http://localhost:3000/bhakti/categories/2

###
// delete category by id
DELETE http://localhost:3000/bhakti/categories/8