// Get All Books
GET http://localhost:3000/book/all
###

//Get Book By Id
GET http://localhost:3000/book/id/11
###

//Delete book by id
DELETE http://localhost:3000/book/delete/10
###

// Get Book By Search
GET http://localhost:3000/book/search?q=B
###

// Get All Book Titles
GET http://localhost:3000/book/booklist
###

// Get All Book Keywords
GET http://localhost:3000/book/keywords
###

// Get Books By Filter of Keywords
GET http://localhost:3000/book/filter?keyword=Rama