// Get All God
GET http://localhost:3000/god
###

// Get God by ID
GET http://localhost:3000/god/2
###

// Get All Keywords of god
GET http://localhost:3000/god/keywords
###

// Get God by search
GET http://localhost:3000/god/search?q=s
###

// Get Trimurti god
GET http://localhost:3000/god/trimurti